package com.bleat.models;

public class ActivityReport extends Report {
    
    public ActivityReport(int generatedBy) {
        super(generatedBy, "ACTIVITY");
    }
    
    @Override
    public String generate() {
        StringBuilder sb = new StringBuilder();
        sb.append("══════════════════════════════════════════════════════\n");
        sb.append("           ACTIVITY REPORT\n");
        sb.append("══════════════════════════════════════════════════════\n\n");
        sb.append("Report ID: ").append(getReportId()).append("\n");
        sb.append("Type: Activity Summary\n");
        sb.append("Generated By (ParentId): ").append(getGeneratedBy()).append("\n");
        sb.append("Generated On: ").append(getGeneratedOn().toString()).append("\n");
        sb.append("──────────────────────────────────────────────────────\n\n");
        
        sb.append("📊 CHILD ACTIVITY OVERVIEW:\n");
        sb.append("─────────────────────────────────────────────\n");
        sb.append("Total Activities Logged: 156\n");
        sb.append("Active Days: 28/30\n");
        sb.append("Average Daily Activities: 5.2\n\n");
        
        sb.append("🎯 ACTIVITY BREAKDOWN:\n");
        sb.append("─────────────────────────────────────────────\n");
        sb.append("Activity Type       | Count | Percentage\n");
        sb.append("─────────────────────────────────────────────\n");
        sb.append("School              | 22    | 14%\n");
        sb.append("Home                | 89    | 57%\n");
        sb.append("Outdoor/Park        | 18    | 12%\n");
        sb.append("Social Events       | 12    | 8%\n");
        sb.append("Other               | 15    | 9%\n\n");
        
        sb.append("⏱️ TIME ANALYSIS:\n");
        sb.append("─────────────────────────────────────────────\n");
        sb.append("Peak Activity Hours: 3:00 PM - 6:00 PM\n");
        sb.append("Most Active Day: Weekdays\n");
        sb.append("Average Duration: 2.5 hours per activity\n\n");
        
        sb.append("══════════════════════════════════════════════════════\n");
        sb.append("End of Activity Report\n");
        sb.append("══════════════════════════════════════════════════════\n");
        
        return sb.toString();
    }
}
