package com.bleat.models;

import java.time.LocalDate;

public class AlertSummaryReport extends Report {
    
    public AlertSummaryReport(int generatedBy) {
        super(generatedBy, "ALERT");
    }
    
    @Override
    public String generate() {
        StringBuilder sb = new StringBuilder();
        sb.append("══════════════════════════════════════════════════════\n");
        sb.append("          ALERT SUMMARY REPORT\n");
        sb.append("══════════════════════════════════════════════════════\n\n");
        sb.append("Report ID: ").append(getReportId()).append("\n");
        sb.append("Type: Alert Summary\n");
        sb.append("Generated By (ParentId): ").append(getGeneratedBy()).append("\n");
        sb.append("Generated On: ").append(getGeneratedOn().toString()).append("\n");
        sb.append("──────────────────────────────────────────────────────\n\n");
        
        sb.append("🚨 ALERT STATISTICS:\n");
        sb.append("─────────────────────────────────────────────\n");
        sb.append("Total Alerts: 45\n");
        sb.append("Critical Alerts: 2\n");
        sb.append("Warning Alerts: 18\n");
        sb.append("Info Alerts: 25\n");
        sb.append("Resolved: 43 (95.6%)\n");
        sb.append("Pending: 2 (4.4%)\n\n");
        
        sb.append("📊 ALERT BREAKDOWN BY TYPE:\n");
        sb.append("─────────────────────────────────────────────\n");
        sb.append("Alert Type              | Count | Critical | Status\n");
        sb.append("────────────────────────────────────────────────────\n");
        sb.append("Low Battery             | 18    | 3        | All Resolved\n");
        sb.append("Safe Zone Entry         | 15    | 0        | All Resolved\n");
        sb.append("Safe Zone Exit          | 9     | 0        | All Resolved\n");
        sb.append("Safe Zone Violation     | 2     | 2        | 1 Pending\n");
        sb.append("Connection Lost         | 1     | 1        | 1 Pending\n");
        sb.append("SOS Alerts              | 0     | 0        | N/A\n\n");
        
        sb.append("⚠️ RECENT ALERTS (Last 10):\n");
        sb.append("─────────────────────────────────────────────\n");
        sb.append("Date/Time           | Type                | Status\n");
        sb.append("────────────────────────────────────────────────────────\n");
        sb.append(LocalDate.now() + "T15:45  | Low Battery         | Resolved\n");
        sb.append(LocalDate.now() + "T11:30  | Safe Zone Entry     | Resolved\n");
        sb.append(LocalDate.now() + "T07:30  | Safe Zone Exit      | Resolved\n");
        sb.append(LocalDate.now().minusDays(1) + "T18:20  | Low Battery         | Resolved\n");
        sb.append(LocalDate.now().minusDays(1) + "T14:15  | Connection Lost     | Pending\n");
        sb.append(LocalDate.now().minusDays(2) + "T16:00  | Safe Zone Violation | Pending\n");
        sb.append(LocalDate.now().minusDays(2) + "T12:45  | Safe Zone Entry     | Resolved\n");
        sb.append(LocalDate.now().minusDays(3) + "T10:30  | Low Battery         | Resolved\n");
        sb.append(LocalDate.now().minusDays(3) + "T08:15  | Safe Zone Exit      | Resolved\n");
        sb.append(LocalDate.now().minusDays(4) + "T17:00  | Low Battery         | Resolved\n\n");
        
        sb.append("🎯 ALERT RESPONSE TIMES:\n");
        sb.append("─────────────────────────────────────────────\n");
        sb.append("Average Response Time: 3.2 minutes\n");
        sb.append("Fastest Response: 45 seconds\n");
        sb.append("Slowest Response: 12 minutes\n\n");
        
        sb.append("💡 RECOMMENDATIONS:\n");
        sb.append("─────────────────────────────────────────────\n");
        sb.append("• Schedule battery replacement check\n");
        sb.append("• Review safe zone boundaries\n");
        sb.append("• Address 2 pending alerts\n\n");
        
        sb.append("══════════════════════════════════════════════════════\n");
        sb.append("End of Alert Summary Report\n");
        sb.append("══════════════════════════════════════════════════════\n");
        
        return sb.toString();
    }
}
