package com.bleat.models;

import java.time.LocalDate;

public class DailyReport extends Report {
    
    public DailyReport(int generatedBy) {
        super(generatedBy, "DAILY");
    }
    
    @Override
    public String generate() {
        StringBuilder sb = new StringBuilder();
        sb.append("══════════════════════════════════════════════════════\n");
        sb.append("           DAILY ACTIVITY REPORT\n");
        sb.append("══════════════════════════════════════════════════════\n\n");
        sb.append("Report ID: ").append(getReportId()).append("\n");
        sb.append("Type: Daily Summary\n");
        sb.append("Generated By (ParentId): ").append(getGeneratedBy()).append("\n");
        sb.append("Generated On: ").append(getGeneratedOn().toString()).append("\n");
        sb.append("Report Date: ").append(LocalDate.now()).append("\n");
        sb.append("──────────────────────────────────────────────────────\n\n");
        
        sb.append("📍 TODAY'S LOCATION SUMMARY:\n");
        sb.append("─────────────────────────────────────────\n");
        sb.append("Total Location Updates: 24\n");
        sb.append("First Check-in: 07:30 AM\n");
        sb.append("Last Check-in: 08:45 PM\n\n");
        
        sb.append("Recent Locations (Last 5 Hours):\n");
        sb.append("Timestamp          | Latitude  | Longitude  | Location\n");
        sb.append("─────────────────────────────────────────────────────────\n");
        sb.append(LocalDate.now() + "T08:45  | 33.6844   | 73.0479   | Home\n");
        sb.append(LocalDate.now() + "T06:30  | 33.6920   | 73.0610   | School\n");
        sb.append(LocalDate.now() + "T04:15  | 33.6920   | 73.0610   | School\n");
        sb.append(LocalDate.now() + "T02:00  | 33.6920   | 73.0610   | School\n");
        sb.append(LocalDate.now() + "T11:30  | 33.6870   | 73.0520   | Park\n\n");
        
        sb.append("🚨 TODAY'S ALERTS:\n");
        sb.append("─────────────────────────────────────────\n");
        sb.append("• " + LocalDate.now() + " 03:45 PM: Low Battery Alert (15%)\n");
        sb.append("• " + LocalDate.now() + " 11:30 AM: Entered Safe Zone (Park)\n");
        sb.append("• " + LocalDate.now() + " 07:30 AM: Left Safe Zone (Home)\n\n");
        
        sb.append("📱 DEVICE STATUS (Today):\n");
        sb.append("─────────────────────────────────────────\n");
        sb.append("• Device Active: 14 hours 15 minutes\n");
        sb.append("• Current Battery: 15%\n");
        sb.append("• Connection Status: Online\n");
        sb.append("• Average Response Time: 2.3 seconds\n\n");
        
        sb.append("══════════════════════════════════════════════════════\n");
        sb.append("End of Daily Report\n");
        sb.append("══════════════════════════════════════════════════════\n");
        
        return sb.toString();
    }
}
