package com.bleat.models;

import java.time.LocalDate;

public class LocationHistoryReport extends Report {
    
    public LocationHistoryReport(int generatedBy) {
        super(generatedBy, "LOCATION");
    }
    
    @Override
    public String generate() {
        StringBuilder sb = new StringBuilder();
        sb.append("══════════════════════════════════════════════════════\n");
        sb.append("        LOCATION HISTORY REPORT\n");
        sb.append("══════════════════════════════════════════════════════\n\n");
        sb.append("Report ID: ").append(getReportId()).append("\n");
        sb.append("Type: Location History\n");
        sb.append("Generated By (ParentId): ").append(getGeneratedBy()).append("\n");
        sb.append("Generated On: ").append(getGeneratedOn().toString()).append("\n");
        sb.append("──────────────────────────────────────────────────────\n\n");
        
        sb.append("📍 LOCATION TRACKING SUMMARY:\n");
        sb.append("─────────────────────────────────────────────\n");
        sb.append("Total Location Updates: 720\n");
        sb.append("Date Range: Last 30 days\n");
        sb.append("GPS Accuracy: ±5 meters\n\n");
        
        sb.append("🗺️ FREQUENTLY VISITED LOCATIONS:\n");
        sb.append("─────────────────────────────────────────────\n");
        sb.append("Location               | Visits | Last Visited\n");
        sb.append("───────────────────────────────────────────────────────\n");
        sb.append("Home                   | 240    | ").append(LocalDate.now()).append("\n");
        sb.append("School                 | 176    | ").append(LocalDate.now().minusDays(1)).append("\n");
        sb.append("Park Area              | 48     | ").append(LocalDate.now().minusDays(2)).append("\n");
        sb.append("Shopping Center        | 32     | ").append(LocalDate.now().minusDays(5)).append("\n");
        sb.append("Friend's House         | 24     | ").append(LocalDate.now().minusDays(7)).append("\n\n");
        
        sb.append("📊 DETAILED LOCATION LOG (Recent 10 Updates):\n");
        sb.append("─────────────────────────────────────────────\n");
        sb.append("Timestamp           | Latitude  | Longitude | Address\n");
        sb.append("────────────────────────────────────────────────────────────\n");
        sb.append(LocalDate.now() + "T20:15  | 33.6844   | 73.0479  | Home\n");
        sb.append(LocalDate.now() + "T15:30  | 33.6920   | 73.0610  | School\n");
        sb.append(LocalDate.now() + "T12:00  | 33.6920   | 73.0610  | School\n");
        sb.append(LocalDate.now() + "T08:30  | 33.6844   | 73.0479  | Home\n");
        sb.append(LocalDate.now().minusDays(1) + "T18:45  | 33.6844   | 73.0479  | Home\n");
        sb.append(LocalDate.now().minusDays(1) + "T15:15  | 33.6920   | 73.0610  | School\n");
        sb.append(LocalDate.now().minusDays(1) + "T12:30  | 33.6920   | 73.0610  | School\n");
        sb.append(LocalDate.now().minusDays(1) + "T08:00  | 33.6844   | 73.0479  | Home\n");
        sb.append(LocalDate.now().minusDays(2) + "T17:30  | 33.6870   | 73.0520  | Park\n");
        sb.append(LocalDate.now().minusDays(2) + "T14:00  | 33.6870   | 73.0520  | Park\n\n");
        
        sb.append("══════════════════════════════════════════════════════\n");
        sb.append("End of Location History Report\n");
        sb.append("══════════════════════════════════════════════════════\n");
        
        return sb.toString();
    }
}
