package com.bleat.models;

import java.time.LocalDate;
import java.time.YearMonth;

public class MonthlyReport extends Report {
    
    public MonthlyReport(int generatedBy) {
        super(generatedBy, "MONTHLY");
    }
    
    @Override
    public String generate() {
        StringBuilder sb = new StringBuilder();
        YearMonth currentMonth = YearMonth.now();
        
        sb.append("══════════════════════════════════════════════════════\n");
        sb.append("         MONTHLY ACTIVITY REPORT\n");
        sb.append("══════════════════════════════════════════════════════\n\n");
        sb.append("Report ID: ").append(getReportId()).append("\n");
        sb.append("Type: Monthly Summary\n");
        sb.append("Generated By (ParentId): ").append(getGeneratedBy()).append("\n");
        sb.append("Generated On: ").append(getGeneratedOn().toString()).append("\n");
        sb.append("Report Month: ").append(currentMonth.getMonth()).append(" ").append(currentMonth.getYear()).append("\n");
        sb.append("──────────────────────────────────────────────────────\n\n");
        
        sb.append("📊 MONTHLY OVERVIEW:\n");
        sb.append("─────────────────────────────────────────\n");
        sb.append("Total Days in Month: ").append(currentMonth.lengthOfMonth()).append("\n");
        sb.append("Days Tracked: ").append(currentMonth.lengthOfMonth()).append("\n");
        sb.append("Total Location Updates: 720\n");
        sb.append("Average Updates/Day: 24\n");
        sb.append("Total Distance Traveled: ~245 km\n\n");
        
        sb.append("📍 LOCATION ANALYTICS:\n");
        sb.append("─────────────────────────────────────────\n");
        sb.append("Location       | Days Visited | Avg Time/Day | Total Hours\n");
        sb.append("────────────────────────────────────────────────────────\n");
        sb.append("Home           | 30           | 10.2 hrs     | 306 hrs\n");
        sb.append("School         | 22           | 6.5 hrs      | 143 hrs\n");
        sb.append("Park           | 8            | 2.1 hrs      | 17 hrs\n");
        sb.append("Shopping Mall  | 4            | 3.0 hrs      | 12 hrs\n");
        sb.append("Other          | 30           | 5.2 hrs      | 156 hrs\n\n");
        
        sb.append("📈 WEEKLY BREAKDOWN:\n");
        sb.append("─────────────────────────────────────────\n");
        sb.append("Week    | Updates | Alerts | Avg Battery | Uptime\n");
        sb.append("───────────────────────────────────────────────────\n");
        sb.append("Week 1  | 168     | 12     | 52%         | 98%\n");
        sb.append("Week 2  | 180     | 8      | 48%         | 99%\n");
        sb.append("Week 3  | 176     | 15     | 45%         | 96%\n");
        sb.append("Week 4  | 196     | 10     | 50%         | 97%\n\n");
        
        sb.append("🚨 MONTHLY ALERT ANALYSIS:\n");
        sb.append("─────────────────────────────────────────\n");
        sb.append("Total Alerts: 45\n\n");
        sb.append("Alert Type              | Count | Percentage\n");
        sb.append("────────────────────────────────────────────\n");
        sb.append("Low Battery             | 18    | 40%\n");
        sb.append("Safe Zone Entry         | 15    | 33%\n");
        sb.append("Safe Zone Exit          | 9     | 20%\n");
        sb.append("Safe Zone Violation     | 2     | 4%\n");
        sb.append("Connection Lost         | 1     | 2%\n");
        sb.append("SOS Alerts              | 0     | 0%\n\n");
        
        sb.append("Most Alert-Heavy Days:\n");
        sb.append("• ").append(LocalDate.now().minusDays(15)).append(": 6 alerts (Battery issues)\n");
        sb.append("• ").append(LocalDate.now().minusDays(8)).append(": 5 alerts (Safe zone)\n");
        sb.append("• ").append(LocalDate.now().minusDays(22)).append(": 4 alerts (Connection)\n\n");
        
        sb.append("📱 DEVICE PERFORMANCE:\n");
        sb.append("─────────────────────────────────────────\n");
        sb.append("• Overall Uptime: 97.5%\n");
        sb.append("• Average Battery Level: 48.75%\n");
        sb.append("• Total Charging Cycles: 28\n");
        sb.append("• GPS Accuracy: ±5 meters (Excellent)\n");
        sb.append("• Network Connectivity: 99.2%\n");
        sb.append("• Failed Location Updates: 3 (0.4%)\n");
        sb.append("• Average Response Time: 2.1 seconds\n\n");
        
        sb.append("🎯 BEHAVIORAL PATTERNS:\n");
        sb.append("─────────────────────────────────────────\n");
        sb.append("• Morning Routine (7-9 AM): Consistent departure from home\n");
        sb.append("• School Hours (9 AM-3 PM): Regular attendance, 22/22 school days\n");
        sb.append("• Afternoon Activity (3-6 PM): Varies - Park, Home, Activities\n");
        sb.append("• Evening (6-10 PM): Primarily at home\n");
        sb.append("• Weekend Pattern: More outdoor activities detected\n\n");
        
        sb.append("✅ SAFETY COMPLIANCE:\n");
        sb.append("─────────────────────────────────────────\n");
        sb.append("• Safe Zone Compliance Rate: 96.5%\n");
        sb.append("• Emergency Response Time: N/A (No emergencies)\n");
        sb.append("• Unauthorized Area Visits: 2 incidents\n");
        sb.append("• Device Tampering Attempts: 0\n\n");
        
        sb.append("🏆 MONTHLY HIGHLIGHTS:\n");
        sb.append("─────────────────────────────────────────\n");
        sb.append("✓ Perfect school attendance record\n");
        sb.append("✓ No emergency situations this month\n");
        sb.append("✓ Excellent device uptime (97.5%)\n");
        sb.append("✓ Consistent safety compliance\n");
        sb.append("⚠ Consider battery replacement (frequent low battery alerts)\n");
        sb.append("ℹ Child spending adequate time outdoors (healthy activity level)\n\n");
        
        sb.append("📋 RECOMMENDATIONS:\n");
        sb.append("─────────────────────────────────────────\n");
        sb.append("1. Schedule device battery health check\n");
        sb.append("2. Review safe zone boundaries for park area\n");
        sb.append("3. Consider adding emergency contact at school\n");
        sb.append("4. Current monitoring settings are optimal\n\n");
        
        sb.append("══════════════════════════════════════════════════════\n");
        sb.append("End of Monthly Report\n");
        sb.append("Generated by BLEAT Child Safety Monitoring System\n");
        sb.append("══════════════════════════════════════════════════════\n");
        
        return sb.toString();
    }
}
