// package com.bleat.models;

// import java.time.LocalDateTime;
// import java.util.concurrent.atomic.AtomicInteger;

// public class Report {
//     private static final AtomicInteger ID_GEN = new AtomicInteger(1);

//     private int reportId;
//     private int generatedBy; // parent userId
//     private LocalDateTime generatedOn;
//     private String type; // e.g., "location_history", "alerts"

//     public Report(int generatedBy, String type) {
//         this.reportId = ID_GEN.getAndIncrement();
//         this.generatedBy = generatedBy;
//         this.type = type;
//         this.generatedOn = LocalDateTime.now();
//     }

//     public String generate() {
//         // In the real system we'd aggregate alerts, locations and device activity.
//         // For local dev return a multi-line sample report with dummy data so the
//         // frontend always has something to display and download.
//         StringBuilder sb = new StringBuilder();
//         sb.append("Report ID: ").append(reportId).append("\n");
//         sb.append("Type: ").append(type).append("\n");
//         sb.append("Generated By (ParentId): ").append(generatedBy).append("\n");
//         sb.append("Generated On: ").append(generatedOn.toString()).append("\n\n");

//         sb.append("Summary:\n");
//         sb.append("- This is a sample report produced for development/testing.\n\n");

//         sb.append("Sample Location History:\n");
//         sb.append("Timestamp, Latitude, Longitude\n");
//         sb.append("2025-11-01T09:12:00, 33.684420, 73.047880\n");
//         sb.append("2025-11-02T12:05:00, 33.685000, 73.048200\n");
//         sb.append("2025-11-07T18:30:00, 33.686100, 73.046900\n\n");

//         sb.append("Sample Alerts (last 7 days):\n");
//         sb.append("- 2025-11-06T14:22: SOS triggered - Battery Low\n");
//         sb.append("- 2025-11-05T08:11: SafeZone exit detected\n\n");

//         sb.append("Device Activity:\n");
//         sb.append("- Device online 95% of period\n");
//         sb.append("- Average location pings per day: 18\n");

//         return sb.toString();
//     }

//     public boolean export(String format) {
//         // supporting "pdf", "csv", "json" placeholders
//         System.out.println("Exporting report " + reportId + " as " + format);
//         return true;
//     }

//     // getters
//     public int getReportId() {
//         return reportId;
//     }

//     public int getGeneratedBy() {
//         return generatedBy;
//     }

//     public LocalDateTime getGeneratedOn() {
//         return generatedOn;
//     }

//     public String getType() {
//         return type;
//     }
// }

package com.bleat.models;

import java.time.LocalDateTime;
import java.util.concurrent.atomic.AtomicInteger;

public abstract class Report {
    
    private static final AtomicInteger ID_GEN = new AtomicInteger(1);
    
    private int reportId;
    private int generatedBy; // parent userId
    private LocalDateTime generatedOn;
    private String type;
    
    public Report(int generatedBy, String type) {
        this.reportId = ID_GEN.getAndIncrement();
        this.generatedBy = generatedBy;
        this.type = type;
        this.generatedOn = LocalDateTime.now();
    }
    
    // Abstract method - each report type implements its own generation logic
    public abstract String generate();
    
    public boolean export(String format) {
        // supporting "pdf", "csv", "json" placeholders
        System.out.println("Exporting report " + reportId + " as " + format);
        return true;
    }
    
    // getters
    public int getReportId() {
        return reportId;
    }
    
    public int getGeneratedBy() {
        return generatedBy;
    }
    
    public LocalDateTime getGeneratedOn() {
        return generatedOn;
    }
    
    public String getType() {
        return type;
    }
}
