package com.bleat.models;

import java.time.LocalDate;

public class WeeklyReport extends Report {
    
    public WeeklyReport(int generatedBy) {
        super(generatedBy, "WEEKLY");
    }
    
    @Override
    public String generate() {
        StringBuilder sb = new StringBuilder();
        LocalDate today = LocalDate.now();
        LocalDate weekStart = today.minusDays(7);
        
        sb.append("══════════════════════════════════════════════════════\n");
        sb.append("          WEEKLY ACTIVITY REPORT\n");
        sb.append("══════════════════════════════════════════════════════\n\n");
        sb.append("Report ID: ").append(getReportId()).append("\n");
        sb.append("Type: Weekly Summary\n");
        sb.append("Generated By (ParentId): ").append(getGeneratedBy()).append("\n");
        sb.append("Generated On: ").append(getGeneratedOn().toString()).append("\n");
        sb.append("Period: ").append(weekStart).append(" to ").append(today).append("\n");
        sb.append("──────────────────────────────────────────────────────\n\n");
        
        sb.append("📊 WEEKLY STATISTICS:\n");
        sb.append("─────────────────────────────────────────\n");
        sb.append("Total Days Tracked: 7\n");
        sb.append("Total Location Updates: 168\n");
        sb.append("Average Updates/Day: 24\n");
        sb.append("Most Active Day: ").append(today.minusDays(2)).append(" (32 updates)\n");
        sb.append("Least Active Day: ").append(today.minusDays(5)).append(" (18 updates)\n\n");
        
        sb.append("📍 LOCATION PATTERN ANALYSIS:\n");
        sb.append("─────────────────────────────────────────\n");
        sb.append("Day        | Primary Location    | Time Spent | Updates\n");
        sb.append("───────────────────────────────────────────────────────\n");
        sb.append(today).append("      | Home               | 8.5 hrs    | 24\n");
        sb.append(today.minusDays(1)).append(" | School             | 6.2 hrs    | 26\n");
        sb.append(today.minusDays(2)).append(" | School             | 7.1 hrs    | 32\n");
        sb.append(today.minusDays(3)).append(" | Home               | 9.0 hrs    | 21\n");
        sb.append(today.minusDays(4)).append(" | School             | 6.5 hrs    | 28\n");
        sb.append(today.minusDays(5)).append(" | Park               | 4.2 hrs    | 18\n");
        sb.append(today.minusDays(6)).append(" | School             | 6.8 hrs    | 19\n\n");
        
        sb.append("🚨 WEEKLY ALERT SUMMARY:\n");
        sb.append("─────────────────────────────────────────\n");
        sb.append("Total Alerts: 15\n");
        sb.append("• Battery Low Alerts: 3\n");
        sb.append("• Safe Zone Violations: 2\n");
        sb.append("• Safe Zone Entries: 8\n");
        sb.append("• Safe Zone Exits: 2\n");
        sb.append("• SOS Alerts: 0\n\n");
        
        sb.append("Critical Events:\n");
        sb.append("• ").append(today.minusDays(3)).append(": Safe Zone violation - Child outside designated area\n");
        sb.append("• ").append(today.minusDays(5)).append(": Battery critically low (5%)\n\n");
        
        sb.append("📱 DEVICE HEALTH (Weekly Average):\n");
        sb.append("─────────────────────────────────────────\n");
        sb.append("• Uptime: 97.5%\n");
        sb.append("• Average Battery Level: 45%\n");
        sb.append("• Connection Quality: Excellent\n");
        sb.append("• GPS Accuracy: ±5 meters\n");
        sb.append("• Data Syncs: 168 successful, 2 failed\n\n");
        
        sb.append("🏆 WEEKLY INSIGHTS:\n");
        sb.append("─────────────────────────────────────────\n");
        sb.append("✓ Child consistently arrives at school on time\n");
        sb.append("✓ Safe zone compliance: 95%\n");
        sb.append("⚠ Battery charging needed more frequently\n");
        sb.append("✓ No emergency situations this week\n\n");
        
        sb.append("══════════════════════════════════════════════════════\n");
        sb.append("End of Weekly Report\n");
        sb.append("══════════════════════════════════════════════════════\n");
        
        return sb.toString();
    }
}
